# Use mysql/example user/password credentials
version: '3.8'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: Admin
      MYSQL_PASSWORD: admin 
      MYSQL_DATABASE: Example 
    volumes:
      #- /mnt/c/users/itay/secure_project/sql_data:/var/lib/mysql
      #- \src\DB\init.sql:/docker-entrypoint-initdb.d/index.sql
    ports:
      - 3306:3306



  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080version: '3.8'

services:

  db:
