# Use mysql/example user/password credentials
version: '3.8'

services:
  database:
    build:
      context: ./sql_data
      dockerfile: Dockerfile
    ports:
      - "3456:3456"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
