# Use mysql/example user/password credentials
version: '3.8'

services:

  db:
    image: csdb:Dockerfile1.0
    restart: unless-stopped
    ports:
      - 3306:3306


  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
